# Generated by Django 3.0.2 on 2020-01-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.CharField(default='summary', max_length=200),
            preserve_default=False,
        ),
    ]
